[package]
name = "yule"
version = "0.1.0"
edition = "2021"

[dependencies]
re = { path = "../retrofire/core", package = "retrofire-core", features = ["std"] }
re-front = { path = "../retrofire/front", package = "retrofire-front", features = ["minifb"] }
minifb = { version = "0.27.0" }
